[package]
name = "pyth-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyth-client = "0.3.0"
solana-sdk = "1.8.11"

